# gestisco le proprietà del mio progetto, quali porta di accesso 


spring.application.name=demo


server.port = 8082


# logging.level: Indica che vuoi configurare la soglia di visibilità dei messaggi.

# .root: Si riferisce a tutta l'applicazione (comprese le librerie esterne come Tomcat, Hibernate, ecc.). È il livello gerarchico più alto.

# = INFO: È il livello di severità.
logging.level.root = INFO